version: '2.2'

services:   
  database:
    image: postgres
    environment:
      - POSTGRES_USER=ping
      - POSTGRES_PASSWORD=pong
      - POSTGRES_DB=pong_db
    ports:
      - 5432:5432
    volumes: 
      - database:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: 'Dockerfile'
    ports:
      - '3001:3001'
  frontend:
    build:
      context: ./frontend
      dockerfile: 'Dockerfile'
    ports:
      - 80:80


volumes:
  database: {}